version: '3'


networks:
    Docker_Net:
      name: Docker_net
      external: true
      driver: macvlan
      driver_opts:
        parent: "Interface"
      ipam:
        config:
           - subnet: DockerSubnet
             gateway: Docker_Gateway

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root_PASSWORD
      MYSQL_USER:  USERNAME
      MYSQL_PASSWORD: DB_PASSWORD
#    expose:
#        - ""
    ports:
        - "3306:3306"
    volumes:
     - ./data/mysql:/var/lib/mysql
    networks:
      TR_NAM_Docker:
        ipv4_address: MariaDB_IP
              
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      TR_NAM_Docker:
        ipv4_address: PHPMYADMIN_IP
